### Get all banners
GET http://localhost:3000/banner
Content-Type: application/json
Accept: application/json

### Create banner
POST http://localhost:3000/banner
Content-Type: application/json
Accept: application/json

{
  "name": "testName",
  "title": "testTitle",
  "description": "testDescription",
  "imageUrl": "http://www.naver.com",
  "orderNo": "1"
}

### Update banner
PUT http://localhost:3000/banner/4
Content-Type: application/json
Accept: application/json

{
  "name": "testName5",
  "title": "testTitle5",
  "description": "1testDescription5",
  "imageUrl": "http://www.naver.com5",
  "orderNo": "5"
}

### Delete banner
DELETE http://localhost:3000/banner/2
Content-Type: application/json
Accept: application/json
